[twitch]
client_id = ""
client_secret = ""
target_channel = ""
moderators = []

[discord]
enabled = false
token = ""

[features]
tts = false

[markov]
train_on_chat = true
ngram_path = "data.pkl"
split_strategy = "character"
character_count = 4
autosave_interval = 50
length_to_generate = 200
max_retries = 3
cooldown = 0

[moderation]
ignored_users = ["streamelements", "creatisbot", "nightbot", "fossabot"]
bad_words = []

[ollama]
host = "192.168.0.101:11434"
model = "mistral:latest"
num_predict = 80
max_history = 80

[logging]
log_all_messages = false