[twitch]
user = ""
# https://dev.twitch.tv/console
# https://twitchtokengenerator.com
client_id = ""
client_secret = ""
user_access_token = ""
refresh_token = ""


[bot]
prefix = "!"
channels = ["your_channel_here"]
ignored_users = ["streamelements", "creatisbot", "nightbot", "fossabot"]

[ollama]
host = "192.168.0.101:11434"
model = "mistral:latest"
num_predict = 80
max_history = 80

[markov]
autosave_interval = 50
length_to_generate = 200

[[notifications]]
# twitch_channel = "channel_name"
# discord_webhook = "https://discord.com/api/webhooks/..."
# message = "{{channel}} is now live playing {{game}}! https://twitch.tv/{{channel}}"