package commands

import (
	"math/rand/v2"
	"pizza-son/internal/bot"
)

var eightBallResponses = []string{
	"As I see it, yes.",
	"Ask again later.",
	"Better not tell you now.",
	"Cannot predict now.",
	"Concentrate and ask again.",
	"Don't count on it.",
	"It is certain.",
	"It is decidedly so.",
	"Most likely.",
	"My reply is no.",
	"My sources say no.",
	"Outlook not so good.",
	"Outlook good.",
	"Reply hazy, try again.",
	"Signs point to yes.",
	"Very doubtful.",
	"Without a doubt.",
	"Yes.",
	"Yes, definitely.",
	"You may rely on it.",
	"How did you even get in this situation?",
	"Ask your mom - mom knows best.",
	"NO NO NO!!!",
	"YES YES YES!!!",
	"Bet your house on it.",
	"Leave.",
	"Perform a coin toss.",
	"If you believe really hard, yes.",
	"Not with that attitude.",
	`"No ignorance, no sublimation" - Confucius.`,
	"Only you can decide.",
	"404 - Quote not found.",
	"Shake me harder daddy.",
	"Go for it; your life depends on it.",
	"Alas. No.",
	"Your guess is as good as mine.",
	"SOMEHOW, no.",
	"You already know the answer.",
	"Is this really the question you should be asking?",
	"Do pigs fly?",
	"-.-- . ...",
	"-. ---",
	"This knowledge is kept even from me.",
	"You're better off not knowing",
	"Telling you now would spoil all the fun.",
	`"_______" the blank response spells disaster.`,
	"Only once the gods intervene.",
	"At sundown the answer will be clear.",
	"Fuck no.",
	"Why are you asking a toy to determine your choices?",
	"Fuck it, what could go wrong?",
	"Jesus Christ, No!",
	"You must be either stupid or desperate to ask me.",
	"Help I'm alive and scared.",
	"Ask the Bard.",
	"Sssuuuuurrreee?",
	"HA- No.",
	"God, Yes.",
	"Ja",
	"Nein",
	"42",
	"A definite maybe, possibly.",
	"Ask me again in 10 minutes.",
	"Could you rephrase the question?",
	"Don't hold your breath.",
	"How committed are you to this plan of action?",
	"How could it possibly go wrong?",
	"Run! Now! Don't look back!",
	"The odds are 3720 to 1 against.",
	"We have been trying to reach you about your car's extended warranty.",
	"You have a better chance of being struck by lightning.",
	"Only if you believe.",
	"Once in a blue moon.",
	"Provided no one notices, yes.",
	"It wouldn't be the right thing to do, but sure.",
	"Oh, that's awful! How can you even ask that? But yeah, depressingly.",
	"Drink me. (Bottle top magically appears. The liquid either tastes like yes or no. No explanation given).",
	"Why do I need to know this?",
	"To be honest this problem sounds like something that is beyond my help, you should see a psychiatrist or something.",
	"Ask me again yesterday.",
	"Fuck around and find out!",
	"Bitch, I might!",
	"Play stupid games, win stupid prizes.",
	"Ours is not to reason why. Ours is but to do and die.",
	"For great justice! Take off every zig!",
	"Set it on fire!",
	"Consult a physician if symptoms persist.",
	"Throw a bigger rock at it.",
	"That sounds like a you problem.",
	"I won't tell if you dont.",
	"Let's not and say we did.",
	"I don't know! Ask your Father!",
	"Dancer's choice.",
	"It's your funeral.",
	"...or, now hear me out on this one, we kill the jester.",
	"Who am I to get in the way of a good time?",
	"Maybe you should sleep on it.",
	"Mom said no.",
	"Ask Jon",
}

func init() {
	Register(bot.Command{
		Name:        "8ball",
		Description: "Get an accurate answer for any question you desire.",
		Usage:       "!8ball <text>",
		Handler: func(ctx bot.CommandContext) {
			if len(ctx.Args) == 0 {
				ctx.Client.Reply(ctx.Message.Channel, ctx.Message.ID, "Ask a question!")
				return
			}
			response := eightBallResponses[rand.IntN(len(eightBallResponses))]
			ctx.Client.Reply(ctx.Message.Channel, ctx.Message.ID, "🎱 "+response)
		},
	})
}
