name: deploy-docs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - uses: actions/checkout@v3

      # 2. Set up Python
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mkdocs mkdocs-material

      # # 4. Install your project locally
      # - name: Install project
      #   run: pip install -e .

      # 5. Generate docs
      - name: Generate documentation
        run: python generate_docs.py

      # 6. Deploy to GitHub Pages
      - name: Deploy MkDocs to GitHub Pages
        run: mkdocs gh-deploy --force
